name: Bump version

on:
  push:
    branches:
      - main
    paths-ignore:
      - package.json
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: yarn test

  bump-version:
    if: github.ref == 'refs/heads/main'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      # - name: Install
      #   run: |
      #     yarn install

      # - name: "Aaaa"
      #   uses: actions/github-script@v2
      #   with:
      #     script: |
      #       require(`${process.env.GITHUB_WORKSPACE}/src/action.js`);

      - name: Set creator
        run: |
          git config user.email "automated-version@users.noreply.github.com"
          git config user.name "Automated Version"

      - name: Increment version
        env:
          VERSION_TYPE: ${{ (startsWith(github.event.head_commit.message, 'BREAKING CHANGE:') || contains(toJSON(github.event.head_commit.message), '\n\nBREAKING CHANGE:')) && 'major' || (startsWith(github.event.head_commit.message, 'fix:') || contains(toJSON(github.event.head_commit.message), '\n\nfix:')) && 'patch' || 'minor' }}
        run: |
          npm version $VERSION_TYPE -m "v%s"
          VERSION=$(node -p "require('./package.json').version")

      - name: Push changes
        run: |
          git push --follow-tags
          git push --tags

      # - name: Publish package
      #   run: |
      #     npm config set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
      #     npm publish
